//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace music_portal_asp.net.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("music_portal_asp.net.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступ запрещён.
        /// </summary>
        public static string AccessDeniedHeader {
            get {
                return ResourceManager.GetString("AccessDeniedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У вас нет прав для просмотра этой страницы..
        /// </summary>
        public static string AccessDeniedText {
            get {
                return ResourceManager.GetString("AccessDeniedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действия.
        /// </summary>
        public static string ActionsColumn {
            get {
                return ResourceManager.GetString("ActionsColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить жанр.
        /// </summary>
        public static string AddGenreLink {
            get {
                return ResourceManager.GetString("AddGenreLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все жанры.
        /// </summary>
        public static string AllGenres {
            get {
                return ResourceManager.GetString("AllGenres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уже есть аккаунт?.
        /// </summary>
        public static string AlreadyHaveAccount {
            get {
                return ResourceManager.GetString("AlreadyHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Применить.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Одобрить.
        /// </summary>
        public static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Одобрен.
        /// </summary>
        public static string ApprovedColumn {
            get {
                return ResourceManager.GetString("ApprovedColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Одобрен.
        /// </summary>
        public static string ApprovedLabel {
            get {
                return ResourceManager.GetString("ApprovedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исполнитель.
        /// </summary>
        public static string ArtistFieldLabel {
            get {
                return ResourceManager.GetString("ArtistFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исполнитель.
        /// </summary>
        public static string ArtistLabel {
            get {
                return ResourceManager.GetString("ArtistLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сценическое имя (если выбрали роль Исполнителя).
        /// </summary>
        public static string ArtistNameLabel {
            get {
                return ResourceManager.GetString("ArtistNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя исполнителя не должно превышать 100 символов.
        /// </summary>
        public static string ArtistNameLength {
            get {
                return ResourceManager.GetString("ArtistNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите исполнителя.
        /// </summary>
        public static string ArtistRequired {
            get {
                return ResourceManager.GetString("ArtistRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исполнители.
        /// </summary>
        public static string ArtistsHeader {
            get {
                return ResourceManager.GetString("ArtistsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О себе / Биография.
        /// </summary>
        public static string BioFieldLabel {
            get {
                return ResourceManager.GetString("BioFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Биография.
        /// </summary>
        public static string BioLabel {
            get {
                return ResourceManager.GetString("BioLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание не должно превышать 1000 символов.
        /// </summary>
        public static string BioLength {
            get {
                return ResourceManager.GetString("BioLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По прослушиваниям.
        /// </summary>
        public static string ByPlays {
            get {
                return ResourceManager.GetString("ByPlays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По рейтингу.
        /// </summary>
        public static string ByRating {
            get {
                return ResourceManager.GetString("ByRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По названию.
        /// </summary>
        public static string ByTitle {
            get {
                return ResourceManager.GetString("ByTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Каталог песен.
        /// </summary>
        public static string CatalogHeader {
            get {
                return ResourceManager.GetString("CatalogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите язык.
        /// </summary>
        public static string ChooseLang {
            get {
                return ResourceManager.GetString("ChooseLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле должно быть установлено..
        /// </summary>
        public static string CommentRequired {
            get {
                return ResourceManager.GetString("CommentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарии.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждение пароля.
        /// </summary>
        public static string ConfirmPasswordLabel {
            get {
                return ResourceManager.GetString("ConfirmPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить жанр? Он будет отвязан от всех песен..
        /// </summary>
        public static string DeleteGenreConfirm {
            get {
                return ResourceManager.GetString("DeleteGenreConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить песню безвозвратно?.
        /// </summary>
        public static string DeletePermanentConfirm {
            get {
                return ResourceManager.GetString("DeletePermanentConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить песню?.
        /// </summary>
        public static string DeleteSongConfirm {
            get {
                return ResourceManager.GetString("DeleteSongConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить пользователя? Его исполнительский профиль и песни будут сохранены..
        /// </summary>
        public static string DeleteUserConfirm {
            get {
                return ResourceManager.GetString("DeleteUserConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подробнее.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скачать.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать жанр.
        /// </summary>
        public static string EditGenreHeader {
            get {
                return ResourceManager.GetString("EditGenreHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование песни.
        /// </summary>
        public static string EditSongHeader {
            get {
                return ResourceManager.GetString("EditSongHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование пользователя.
        /// </summary>
        public static string EditUserHeader {
            get {
                return ResourceManager.GetString("EditUserHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EmailColumn {
            get {
                return ResourceManager.GetString("EmailColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректный формат Email.
        /// </summary>
        public static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Электронная почта.
        /// </summary>
        public static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите Email.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Что-то пошло не так.
        /// </summary>
        public static string ErrorHeader {
            get {
                return ResourceManager.GetString("ErrorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла непредвиденная ошибка. Попробуйте вернуться на главную..
        /// </summary>
        public static string ErrorText {
            get {
                return ResourceManager.GetString("ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Форматы: mp3, wav, flac, ogg. Максимум 50 МБ..
        /// </summary>
        public static string FileFormatsHint {
            get {
                return ResourceManager.GetString("FileFormatsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аудиофайл (mp3, wav, flac, ogg).
        /// </summary>
        public static string FileLabel {
            get {
                return ResourceManager.GetString("FileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите аудиофайл.
        /// </summary>
        public static string FileRequired {
            get {
                return ResourceManager.GetString("FileRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жанр.
        /// </summary>
        public static string Genre {
            get {
                return ResourceManager.GetString("Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название не должно превышать 50 символов.
        /// </summary>
        public static string GenreNameLength {
            get {
                return ResourceManager.GetString("GenreNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите название жанра.
        /// </summary>
        public static string GenreNameRequired {
            get {
                return ResourceManager.GetString("GenreNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жанры.
        /// </summary>
        public static string GenresHeader {
            get {
                return ResourceManager.GetString("GenresHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жанры.
        /// </summary>
        public static string GenresLabel {
            get {
                return ResourceManager.GetString("GenresLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите хотя бы один жанр.
        /// </summary>
        public static string GenresRequired {
            get {
                return ResourceManager.GetString("GenresRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string LoginHeader {
            get {
                return ResourceManager.GetString("LoginHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        public static string LoginLink {
            get {
                return ResourceManager.GetString("LoginLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войдите, чтобы оценить песню и оставить комментарий..
        /// </summary>
        public static string LoginToRateAndComment {
            get {
                return ResourceManager.GetString("LoginToRateAndComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + клик чтобы выбрать несколько..
        /// </summary>
        public static string MultiSelectHint {
            get {
                return ResourceManager.GetString("MultiSelectHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string NameColumn {
            get {
                return ResourceManager.GetString("NameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исполнители.
        /// </summary>
        public static string NavArtists {
            get {
                return ResourceManager.GetString("NavArtists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жанры.
        /// </summary>
        public static string NavGenres {
            get {
                return ResourceManager.GetString("NavGenres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заявки.
        /// </summary>
        public static string NavRequests {
            get {
                return ResourceManager.GetString("NavRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Песни.
        /// </summary>
        public static string NavSongs {
            get {
                return ResourceManager.GetString("NavSongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить песню.
        /// </summary>
        public static string NavUpload {
            get {
                return ResourceManager.GetString("NavUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователи.
        /// </summary>
        public static string NavUsers {
            get {
                return ResourceManager.GetString("NavUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый исполнитель.
        /// </summary>
        public static string NewArtistHeader {
            get {
                return ResourceManager.GetString("NewArtistHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Новый исполнитель.
        /// </summary>
        public static string NewArtistLink {
            get {
                return ResourceManager.GetString("NewArtistLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый жанр.
        /// </summary>
        public static string NewGenreHeader {
            get {
                return ResourceManager.GetString("NewGenreHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет аккаунта?.
        /// </summary>
        public static string NoAccountYet {
            get {
                return ResourceManager.GetString("NoAccountYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У исполнителя пока нет песен..
        /// </summary>
        public static string NoArtistSongs {
            get {
                return ResourceManager.GetString("NoArtistSongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исполнителей пока нет..
        /// </summary>
        public static string NoArtistsYet {
            get {
                return ResourceManager.GetString("NoArtistsYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментариев пока нет..
        /// </summary>
        public static string NoComments {
            get {
                return ResourceManager.GetString("NoComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новых заявок нет..
        /// </summary>
        public static string NoPendingRequests {
            get {
                return ResourceManager.GetString("NoPendingRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Песни не найдены.
        /// </summary>
        public static string NoSongsFound {
            get {
                return ResourceManager.GetString("NoSongsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль должен быть не менее 6 символов.
        /// </summary>
        public static string PasswordLength {
            get {
                return ResourceManager.GetString("PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите пароль.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароли не совпадают.
        /// </summary>
        public static string PasswordsMismatch {
            get {
                return ResourceManager.GetString("PasswordsMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заявки на регистрацию.
        /// </summary>
        public static string PendingUsersHeader {
            get {
                return ResourceManager.GetString("PendingUsersHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прослушивания.
        /// </summary>
        public static string PlayCountLabel {
            get {
                return ResourceManager.GetString("PlayCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прослушиваний.
        /// </summary>
        public static string PlaysLabel {
            get {
                return ResourceManager.GetString("PlaysLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рейтинг.
        /// </summary>
        public static string RatingLabel {
            get {
                return ResourceManager.GetString("RatingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата регистрации.
        /// </summary>
        public static string RegDateColumn {
            get {
                return ResourceManager.GetString("RegDateColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрироваться как Исполнитель (требует подтверждения).
        /// </summary>
        public static string RegisterAsArtist {
            get {
                return ResourceManager.GetString("RegisterAsArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string RegisterHeader {
            get {
                return ResourceManager.GetString("RegisterHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрироваться.
        /// </summary>
        public static string RegisterLink {
            get {
                return ResourceManager.GetString("RegisterLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to После регистрации ваша заявка будет рассмотрена администратором портала..
        /// </summary>
        public static string RegisterNotice {
            get {
                return ResourceManager.GetString("RegisterNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спасибо за регистрацию!.
        /// </summary>
        public static string RegistrationPendingHeader {
            get {
                return ResourceManager.GetString("RegistrationPendingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваша заявка отправлена администратору портала. Как только аккаунт будет одобрен, вы сможете войти и пользоваться порталом..
        /// </summary>
        public static string RegistrationPendingText {
            get {
                return ResourceManager.GetString("RegistrationPendingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отклонить.
        /// </summary>
        public static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отклонить и удалить заявку?.
        /// </summary>
        public static string RejectConfirm {
            get {
                return ResourceManager.GetString("RejectConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запомнить меня.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Роли.
        /// </summary>
        public static string RolesColumn {
            get {
                return ResourceManager.GetString("RolesColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Роли.
        /// </summary>
        public static string RolesLabel {
            get {
                return ResourceManager.GetString("RolesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to — выберите исполнителя —.
        /// </summary>
        public static string SelectArtistPlaceholder {
            get {
                return ResourceManager.GetString("SelectArtistPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Музыкальный портал.
        /// </summary>
        public static string SiteTitle {
            get {
                return ResourceManager.GetString("SiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to песен.
        /// </summary>
        public static string SongsCountLabel {
            get {
                return ResourceManager.GetString("SongsCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Песни.
        /// </summary>
        public static string SongsHeader {
            get {
                return ResourceManager.GetString("SongsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сортировка.
        /// </summary>
        public static string SortBy {
            get {
                return ResourceManager.GetString("SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string TitleLabel {
            get {
                return ResourceManager.GetString("TitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название не должно превышать 150 символов.
        /// </summary>
        public static string TitleLength {
            get {
                return ResourceManager.GetString("TitleLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите название песни.
        /// </summary>
        public static string TitleRequired {
            get {
                return ResourceManager.GetString("TitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На главную.
        /// </summary>
        public static string ToHome {
            get {
                return ResourceManager.GetString("ToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to К странице входа.
        /// </summary>
        public static string ToLoginPage {
            get {
                return ResourceManager.GetString("ToLoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Попробуйте изменить параметры фильтрации или загрузить новую песню..
        /// </summary>
        public static string TryChangeFilters {
            get {
                return ResourceManager.GetString("TryChangeFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата загрузки.
        /// </summary>
        public static string UploadDateLabel {
            get {
                return ResourceManager.GetString("UploadDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to загружено.
        /// </summary>
        public static string UploadedOn {
            get {
                return ResourceManager.GetString("UploadedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить песню.
        /// </summary>
        public static string UploadSongHeader {
            get {
                return ResourceManager.GetString("UploadSongHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя должно быть от 3 до 100 символов.
        /// </summary>
        public static string UsernameLength {
            get {
                return ResourceManager.GetString("UsernameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите имя пользователя.
        /// </summary>
        public static string UsernameRequired {
            get {
                return ResourceManager.GetString("UsernameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователи.
        /// </summary>
        public static string UsersHeader {
            get {
                return ResourceManager.GetString("UsersHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш комментарий....
        /// </summary>
        public static string YourComment {
            get {
                return ResourceManager.GetString("YourComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваша оценка.
        /// </summary>
        public static string YourRating {
            get {
                return ResourceManager.GetString("YourRating", resourceCulture);
            }
        }
    }
}
