//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace music_portal_asp.net.Resources
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource()
        {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("music_portal_asp.net.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        public static string AccessDeniedHeader
        {
            get { return ResourceManager.GetString("AccessDeniedHeader", resourceCulture); }
        }
        public static string AccessDeniedText
        {
            get { return ResourceManager.GetString("AccessDeniedText", resourceCulture); }
        }
        public static string ActionsColumn
        {
            get { return ResourceManager.GetString("ActionsColumn", resourceCulture); }
        }
        public static string AddGenreLink
        {
            get { return ResourceManager.GetString("AddGenreLink", resourceCulture); }
        }
        public static string AllGenres
        {
            get { return ResourceManager.GetString("AllGenres", resourceCulture); }
        }
        public static string AlreadyHaveAccount
        {
            get { return ResourceManager.GetString("AlreadyHaveAccount", resourceCulture); }
        }
        public static string Apply
        {
            get { return ResourceManager.GetString("Apply", resourceCulture); }
        }
        public static string Approve
        {
            get { return ResourceManager.GetString("Approve", resourceCulture); }
        }
        public static string ApprovedColumn
        {
            get { return ResourceManager.GetString("ApprovedColumn", resourceCulture); }
        }
        public static string ApprovedLabel
        {
            get { return ResourceManager.GetString("ApprovedLabel", resourceCulture); }
        }
        public static string ArtistFieldLabel
        {
            get { return ResourceManager.GetString("ArtistFieldLabel", resourceCulture); }
        }
        public static string ArtistLabel
        {
            get { return ResourceManager.GetString("ArtistLabel", resourceCulture); }
        }
        public static string ArtistNameLabel
        {
            get { return ResourceManager.GetString("ArtistNameLabel", resourceCulture); }
        }
        public static string ArtistNameLength
        {
            get { return ResourceManager.GetString("ArtistNameLength", resourceCulture); }
        }
        public static string ArtistRequired
        {
            get { return ResourceManager.GetString("ArtistRequired", resourceCulture); }
        }
        public static string ArtistsHeader
        {
            get { return ResourceManager.GetString("ArtistsHeader", resourceCulture); }
        }
        public static string BioFieldLabel
        {
            get { return ResourceManager.GetString("BioFieldLabel", resourceCulture); }
        }
        public static string BioLabel
        {
            get { return ResourceManager.GetString("BioLabel", resourceCulture); }
        }
        public static string BioLength
        {
            get { return ResourceManager.GetString("BioLength", resourceCulture); }
        }
        public static string ByPlays
        {
            get { return ResourceManager.GetString("ByPlays", resourceCulture); }
        }
        public static string ByRating
        {
            get { return ResourceManager.GetString("ByRating", resourceCulture); }
        }
        public static string ByTitle
        {
            get { return ResourceManager.GetString("ByTitle", resourceCulture); }
        }
        public static string Cancel
        {
            get { return ResourceManager.GetString("Cancel", resourceCulture); }
        }
        public static string CatalogHeader
        {
            get { return ResourceManager.GetString("CatalogHeader", resourceCulture); }
        }
        public static string ChooseLang
        {
            get { return ResourceManager.GetString("ChooseLang", resourceCulture); }
        }
        public static string CommentRequired
        {
            get { return ResourceManager.GetString("CommentRequired", resourceCulture); }
        }
        public static string Comments
        {
            get { return ResourceManager.GetString("Comments", resourceCulture); }
        }
        public static string ConfirmPasswordLabel
        {
            get { return ResourceManager.GetString("ConfirmPasswordLabel", resourceCulture); }
        }
        public static string Create
        {
            get { return ResourceManager.GetString("Create", resourceCulture); }
        }
        public static string Delete
        {
            get { return ResourceManager.GetString("Delete", resourceCulture); }
        }
        public static string DeleteGenreConfirm
        {
            get { return ResourceManager.GetString("DeleteGenreConfirm", resourceCulture); }
        }
        public static string DeletePermanentConfirm
        {
            get { return ResourceManager.GetString("DeletePermanentConfirm", resourceCulture); }
        }
        public static string DeleteSongConfirm
        {
            get { return ResourceManager.GetString("DeleteSongConfirm", resourceCulture); }
        }
        public static string DeleteUserConfirm
        {
            get { return ResourceManager.GetString("DeleteUserConfirm", resourceCulture); }
        }
        public static string Details
        {
            get { return ResourceManager.GetString("Details", resourceCulture); }
        }
        public static string Download
        {
            get { return ResourceManager.GetString("Download", resourceCulture); }
        }
        public static string Edit
        {
            get { return ResourceManager.GetString("Edit", resourceCulture); }
        }
        public static string EditGenreHeader
        {
            get { return ResourceManager.GetString("EditGenreHeader", resourceCulture); }
        }
        public static string EditSongHeader
        {
            get { return ResourceManager.GetString("EditSongHeader", resourceCulture); }
        }
        public static string EditUserHeader
        {
            get { return ResourceManager.GetString("EditUserHeader", resourceCulture); }
        }
        public static string EmailColumn
        {
            get { return ResourceManager.GetString("EmailColumn", resourceCulture); }
        }
        public static string EmailInvalid
        {
            get { return ResourceManager.GetString("EmailInvalid", resourceCulture); }
        }
        public static string EmailLabel
        {
            get { return ResourceManager.GetString("EmailLabel", resourceCulture); }
        }
        public static string EmailRequired
        {
            get { return ResourceManager.GetString("EmailRequired", resourceCulture); }
        }
        public static string ErrorHeader
        {
            get { return ResourceManager.GetString("ErrorHeader", resourceCulture); }
        }
        public static string ErrorText
        {
            get { return ResourceManager.GetString("ErrorText", resourceCulture); }
        }
        public static string FileFormatsHint
        {
            get { return ResourceManager.GetString("FileFormatsHint", resourceCulture); }
        }
        public static string FileLabel
        {
            get { return ResourceManager.GetString("FileLabel", resourceCulture); }
        }
        public static string FileRequired
        {
            get { return ResourceManager.GetString("FileRequired", resourceCulture); }
        }
        public static string Genre
        {
            get { return ResourceManager.GetString("Genre", resourceCulture); }
        }
        public static string GenreNameLength
        {
            get { return ResourceManager.GetString("GenreNameLength", resourceCulture); }
        }
        public static string GenreNameRequired
        {
            get { return ResourceManager.GetString("GenreNameRequired", resourceCulture); }
        }
        public static string GenresHeader
        {
            get { return ResourceManager.GetString("GenresHeader", resourceCulture); }
        }
        public static string GenresLabel
        {
            get { return ResourceManager.GetString("GenresLabel", resourceCulture); }
        }
        public static string GenresRequired
        {
            get { return ResourceManager.GetString("GenresRequired", resourceCulture); }
        }
        public static string Login
        {
            get { return ResourceManager.GetString("Login", resourceCulture); }
        }
        public static string LoginHeader
        {
            get { return ResourceManager.GetString("LoginHeader", resourceCulture); }
        }
        public static string LoginLink
        {
            get { return ResourceManager.GetString("LoginLink", resourceCulture); }
        }
        public static string LoginToRateAndComment
        {
            get { return ResourceManager.GetString("LoginToRateAndComment", resourceCulture); }
        }
        public static string Logout
        {
            get { return ResourceManager.GetString("Logout", resourceCulture); }
        }
        public static string MultiSelectHint
        {
            get { return ResourceManager.GetString("MultiSelectHint", resourceCulture); }
        }
        public static string NameColumn
        {
            get { return ResourceManager.GetString("NameColumn", resourceCulture); }
        }
        public static string NameLabel
        {
            get { return ResourceManager.GetString("NameLabel", resourceCulture); }
        }
        public static string NavArtists
        {
            get { return ResourceManager.GetString("NavArtists", resourceCulture); }
        }
        public static string NavGenres
        {
            get { return ResourceManager.GetString("NavGenres", resourceCulture); }
        }
        public static string NavRequests
        {
            get { return ResourceManager.GetString("NavRequests", resourceCulture); }
        }
        public static string NavSongs
        {
            get { return ResourceManager.GetString("NavSongs", resourceCulture); }
        }
        public static string NavUpload
        {
            get { return ResourceManager.GetString("NavUpload", resourceCulture); }
        }
        public static string NavUsers
        {
            get { return ResourceManager.GetString("NavUsers", resourceCulture); }
        }
        public static string NewArtistHeader
        {
            get { return ResourceManager.GetString("NewArtistHeader", resourceCulture); }
        }
        public static string NewArtistLink
        {
            get { return ResourceManager.GetString("NewArtistLink", resourceCulture); }
        }
        public static string NewGenreHeader
        {
            get { return ResourceManager.GetString("NewGenreHeader", resourceCulture); }
        }
        public static string No
        {
            get { return ResourceManager.GetString("No", resourceCulture); }
        }
        public static string NoAccountYet
        {
            get { return ResourceManager.GetString("NoAccountYet", resourceCulture); }
        }
        public static string NoArtistSongs
        {
            get { return ResourceManager.GetString("NoArtistSongs", resourceCulture); }
        }
        public static string NoArtistsYet
        {
            get { return ResourceManager.GetString("NoArtistsYet", resourceCulture); }
        }
        public static string NoComments
        {
            get { return ResourceManager.GetString("NoComments", resourceCulture); }
        }
        public static string NoPendingRequests
        {
            get { return ResourceManager.GetString("NoPendingRequests", resourceCulture); }
        }
        public static string NoSongsFound
        {
            get { return ResourceManager.GetString("NoSongsFound", resourceCulture); }
        }
        public static string PasswordLabel
        {
            get { return ResourceManager.GetString("PasswordLabel", resourceCulture); }
        }
        public static string PasswordLength
        {
            get { return ResourceManager.GetString("PasswordLength", resourceCulture); }
        }
        public static string PasswordRequired
        {
            get { return ResourceManager.GetString("PasswordRequired", resourceCulture); }
        }
        public static string PasswordsMismatch
        {
            get { return ResourceManager.GetString("PasswordsMismatch", resourceCulture); }
        }
        public static string PendingUsersHeader
        {
            get { return ResourceManager.GetString("PendingUsersHeader", resourceCulture); }
        }
        public static string PlayCountLabel
        {
            get { return ResourceManager.GetString("PlayCountLabel", resourceCulture); }
        }
        public static string PlaysLabel
        {
            get { return ResourceManager.GetString("PlaysLabel", resourceCulture); }
        }
        public static string RatingLabel
        {
            get { return ResourceManager.GetString("RatingLabel", resourceCulture); }
        }
        public static string RegDateColumn
        {
            get { return ResourceManager.GetString("RegDateColumn", resourceCulture); }
        }
        public static string Register
        {
            get { return ResourceManager.GetString("Register", resourceCulture); }
        }
        public static string RegisterAsArtist
        {
            get { return ResourceManager.GetString("RegisterAsArtist", resourceCulture); }
        }
        public static string RegisterHeader
        {
            get { return ResourceManager.GetString("RegisterHeader", resourceCulture); }
        }
        public static string RegisterLink
        {
            get { return ResourceManager.GetString("RegisterLink", resourceCulture); }
        }
        public static string RegisterNotice
        {
            get { return ResourceManager.GetString("RegisterNotice", resourceCulture); }
        }
        public static string RegistrationPendingHeader
        {
            get { return ResourceManager.GetString("RegistrationPendingHeader", resourceCulture); }
        }
        public static string RegistrationPendingText
        {
            get { return ResourceManager.GetString("RegistrationPendingText", resourceCulture); }
        }
        public static string Reject
        {
            get { return ResourceManager.GetString("Reject", resourceCulture); }
        }
        public static string RejectConfirm
        {
            get { return ResourceManager.GetString("RejectConfirm", resourceCulture); }
        }
        public static string RememberMe
        {
            get { return ResourceManager.GetString("RememberMe", resourceCulture); }
        }
        public static string RolesColumn
        {
            get { return ResourceManager.GetString("RolesColumn", resourceCulture); }
        }
        public static string RolesLabel
        {
            get { return ResourceManager.GetString("RolesLabel", resourceCulture); }
        }
        public static string Save
        {
            get { return ResourceManager.GetString("Save", resourceCulture); }
        }
        public static string SelectArtistPlaceholder
        {
            get { return ResourceManager.GetString("SelectArtistPlaceholder", resourceCulture); }
        }
        public static string Send
        {
            get { return ResourceManager.GetString("Send", resourceCulture); }
        }
        public static string SiteTitle
        {
            get { return ResourceManager.GetString("SiteTitle", resourceCulture); }
        }
        public static string SongsCountLabel
        {
            get { return ResourceManager.GetString("SongsCountLabel", resourceCulture); }
        }
        public static string SongsHeader
        {
            get { return ResourceManager.GetString("SongsHeader", resourceCulture); }
        }
        public static string SortBy
        {
            get { return ResourceManager.GetString("SortBy", resourceCulture); }
        }
        public static string TitleLabel
        {
            get { return ResourceManager.GetString("TitleLabel", resourceCulture); }
        }
        public static string TitleLength
        {
            get { return ResourceManager.GetString("TitleLength", resourceCulture); }
        }
        public static string TitleRequired
        {
            get { return ResourceManager.GetString("TitleRequired", resourceCulture); }
        }
        public static string ToHome
        {
            get { return ResourceManager.GetString("ToHome", resourceCulture); }
        }
        public static string ToLoginPage
        {
            get { return ResourceManager.GetString("ToLoginPage", resourceCulture); }
        }
        public static string TryChangeFilters
        {
            get { return ResourceManager.GetString("TryChangeFilters", resourceCulture); }
        }
        public static string Upload
        {
            get { return ResourceManager.GetString("Upload", resourceCulture); }
        }
        public static string UploadDateLabel
        {
            get { return ResourceManager.GetString("UploadDateLabel", resourceCulture); }
        }
        public static string UploadedOn
        {
            get { return ResourceManager.GetString("UploadedOn", resourceCulture); }
        }
        public static string UploadSongHeader
        {
            get { return ResourceManager.GetString("UploadSongHeader", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to Имя пользователя.
        /// </summary>
        public static string UsernameLabel
        {
            get
            {
                return ResourceManager.GetString("UsernameLabel", resourceCulture);
            }
        }

        public static string UsernameLength
        {
            get { return ResourceManager.GetString("UsernameLength", resourceCulture); }
        }
        public static string UsernameRequired
        {
            get { return ResourceManager.GetString("UsernameRequired", resourceCulture); }
        }
        public static string UsersHeader
        {
            get { return ResourceManager.GetString("UsersHeader", resourceCulture); }
        }
        public static string Yes
        {
            get { return ResourceManager.GetString("Yes", resourceCulture); }
        }
        public static string YourComment
        {
            get { return ResourceManager.GetString("YourComment", resourceCulture); }
        }
        public static string YourRating
        {
            get { return ResourceManager.GetString("YourRating", resourceCulture); }
        }
    }
}