// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicPortal.DataAccess.Data;

#nullable disable

namespace MusicPortal.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260826150802_FixUserIsApproved")]
    partial class FixUserIsApproved
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MusicPortal.DataAccess.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Поёт",
                            Name = "Музыкант"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "RE",
                            Name = "Reas",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Bio = "tf",
                            Name = "Музыка"
                        },
                        new
                        {
                            Id = 4,
                            Bio = "fDs",
                            Name = "Sdf"
                        });
                });

            modelBuilder.Entity("MusicPortal.DataAccess.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SongId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SongId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 20, 12, 48, 9, 193, DateTimeKind.Unspecified).AddTicks(9717),
                            SongId = 3,
                            Text = "Ку",
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 8, 25, 23, 16, 32, 978, DateTimeKind.Unspecified).AddTicks(934),
                            SongId = 2,
                            Text = "gt",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("MusicPortal.DataAccess.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Музыкаre"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Музыкант"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Рок"
                        },
                        new
                        {
                            Id = 4,
                            Name = "movie-asp.net-mvc"
                        },
                        new
                        {
                            Id = 5,
                            Name = "string"
                        },
                        new
                        {
                            Id = 6,
                            Name = "string"
                        },
                        new
                        {
                            Id = 7,
                            Name = "string"
                        });
                });

            modelBuilder.Entity("MusicPortal.DataAccess.Models.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SongId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SongId");

                    b.HasIndex("UserId", "SongId")
                        .IsUnique();

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            SongId = 2,
                            UserId = 1,
                            Value = 5
                        },
                        new
                        {
                            Id = 3,
                            SongId = 3,
                            UserId = 1,
                            Value = 4
                        });
                });

            modelBuilder.Entity("MusicPortal.DataAccess.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "User"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Artist"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Pending"
                        });
                });

            modelBuilder.Entity("MusicPortal.DataAccess.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlayCount")
                        .HasColumnType("int");

                    b.Property<double>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            ArtistId = 1,
                            FilePath = "/uploads/songs/6ce779ef-29f4-4ecd-9780-e989e6b4f6e7.mp3",
                            PlayCount = 0,
                            Rating = 5.0,
                            Title = "Песня 1",
                            UploadDate = new DateTime(2026, 8, 26, 15, 8, 1, 848, DateTimeKind.Utc).AddTicks(407)
                        },
                        new
                        {
                            Id = 3,
                            ArtistId = 1,
                            FilePath = "/uploads/songs/7e0cedd2-3379-4da6-a7ff-76223ebed9b1.mp3",
                            PlayCount = 0,
                            Rating = 4.0,
                            Title = "Песня 2",
                            UploadDate = new DateTime(2026, 8, 26, 15, 8, 1, 848, DateTimeKind.Utc).AddTicks(1100)
                        },
                        new
                        {
                            Id = 4,
                            ArtistId = 2,
                            FilePath = "/uploads/songs/6ce779ef-29f4-4ecd-9780-e989e6b4f6e7.mp3",
                            PlayCount = 0,
                            Rating = 0.0,
                            Title = "Песня 3",
                            UploadDate = new DateTime(2026, 8, 26, 15, 8, 1, 848, DateTimeKind.Utc).AddTicks(1103)
                        },
                        new
                        {
                            Id = 5,
                            ArtistId = 1,
                            FilePath = "/uploads/songs/df34ccce-986f-4191-886d-59c848541446.mp3",
                            PlayCount = 0,
                            Rating = 0.0,
                            Title = "Песня 4",
                            UploadDate = new DateTime(2026, 8, 26, 15, 8, 1, 848, DateTimeKind.Utc).AddTicks(1105)
                        });
                });

            modelBuilder.Entity("MusicPortal.DataAccess.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 8, 26, 15, 8, 1, 847, DateTimeKind.Utc).AddTicks(6847),
                            Email = "admin@gmail.com",
                            IsApproved = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEPFXVCoAGGUMBXoztUUqpA7fF/Q++PPdjr6YS1gOcF0Zsy71lwAQ7ZKG2ODK6c3SFA==",
                            Username = "admin@gmail.com"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 8, 26, 15, 8, 1, 847, DateTimeKind.Utc).AddTicks(7432),
                            Email = "Ufrseg@gmail.com",
                            IsApproved = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEHOI/ldB8Glyb742DsfFgtuivnInziJ0de0fIi1ragjEQkuxEEMkTQnngilAfzcZvQ==",
                            Username = "Ufrseg"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 8, 26, 15, 8, 1, 847, DateTimeKind.Utc).AddTicks(7435),
                            Email = "ab21506a@gmail.com",
                            IsApproved = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEOVd22mqA1OXfJgD9IlpIOQWgPvkWkZskdEsjAfJJ00pgGAPqJa32H7d75EOGMswtg==",
                            Username = "ab21506A"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 8, 26, 15, 8, 1, 847, DateTimeKind.Utc).AddTicks(7436),
                            Email = "string@gmail.com",
                            IsApproved = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEKgCQ0N4wM7QKgYXrh88fYIqMy/XmogWpgnv8T/Z8w/fgztnlK8WkHyhumSvNcNl6A==",
                            Username = "string"
                        });
                });

            modelBuilder.Entity("SongGenre", b =>
                {
                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<int>("SongId")
                        .HasColumnType("int");

                    b.HasKey("GenreId", "SongId");

                    b.HasIndex("SongId");

                    b.ToTable("SongGenre");

                    b.HasData(
                        new
                        {
                            GenreId = 2,
                            SongId = 2
                        },
                        new
                        {
                            GenreId = 3,
                            SongId = 2
                        },
                        new
                        {
                            GenreId = 4,
                            SongId = 3
                        },
                        new
                        {
                            GenreId = 5,
                            SongId = 3
                        },
                        new
                        {
                            GenreId = 5,
                            SongId = 4
                        },
                        new
                        {
                            GenreId = 5,
                            SongId = 5
                        });
                });

            modelBuilder.Entity("UserRoles", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            UserId = 1
                        },
                        new
                        {
                            RoleId = 2,
                            UserId = 1
                        },
                        new
                        {
                            RoleId = 3,
                            UserId = 1
                        },
                        new
                        {
                            RoleId = 2,
                            UserId = 2
                        },
                        new
                        {
                            RoleId = 2,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("MusicPortal.DataAccess.Models.Artist", b =>
                {
                    b.HasOne("MusicPortal.DataAccess.Models.User", "User")
                        .WithOne("ArtistProfile")
                        .HasForeignKey("MusicPortal.DataAccess.Models.Artist", "UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("MusicPortal.DataAccess.Models.Comment", b =>
                {
                    b.HasOne("MusicPortal.DataAccess.Models.Song", "Song")
                        .WithMany("Comments")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicPortal.DataAccess.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Song");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MusicPortal.DataAccess.Models.Rating", b =>
                {
                    b.HasOne("MusicPortal.DataAccess.Models.Song", "Song")
                        .WithMany("Ratings")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicPortal.DataAccess.Models.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Song");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MusicPortal.DataAccess.Models.Song", b =>
                {
                    b.HasOne("MusicPortal.DataAccess.Models.Artist", "Artist")
                        .WithMany("Songs")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("SongGenre", b =>
                {
                    b.HasOne("MusicPortal.DataAccess.Models.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicPortal.DataAccess.Models.Song", null)
                        .WithMany()
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserRoles", b =>
                {
                    b.HasOne("MusicPortal.DataAccess.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicPortal.DataAccess.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MusicPortal.DataAccess.Models.Artist", b =>
                {
                    b.Navigation("Songs");
                });

            modelBuilder.Entity("MusicPortal.DataAccess.Models.Song", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("MusicPortal.DataAccess.Models.User", b =>
                {
                    b.Navigation("ArtistProfile");

                    b.Navigation("Comments");

                    b.Navigation("Ratings");
                });
#pragma warning restore 612, 618
        }
    }
}
